/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'njg5kor' at '10/1/15 2:02 PM' with Gradle 2.6
 *
 * @author njg5kor, @date 10/1/15 2:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
